### PR TITLE
Revise project structure for cross-platform use

### PR DESCRIPTION
**Pull request by grovduck**
Very cool project that you've started.  We're eager to use it in our vegetation mapping framework (currently using rpy2 to talk with vegan).

I've tried to standardize the directory structure a bit to conform with what I understand to be [best packaging practices](http://www.jeffknupp.com/blog/2013/08/16/open-sourcing-a-python-project-the-right-way/') although I'm still learning.  Here are the changes I'm proposing:
- Add a bunch of files/directories to `.gitignore` so that they don't get included in the repo
- Remove the .so file to ensure more cross-platform support
- Rework `setup.py` using [rasterio](https://github.com/mapbox/rasterio) as a guide
- Bring 'cythonizing' into main `setup.py` file
- Specified minimum versions for dependencies (these may be a bit strict?)

Let me know if these changes go too far from what you're thinking.  I'm successfully building and using this commit (`python setup.py develop`) on Python 2.7 / Windows 7.

### CODE REVIEW

**Comment by Auerilas** [comment]
Hi Matt. Thanks for the suggestions! I don't see anything in here I won't accept. I hadn't updated my .gitignore and I'm glad you fixed that. 

Jut out of curiousity (and this shows my newness to this), why delete the .so file? That's needed to run the isotonic regression. Is this simply deleted from the repo, but when I build and submit to PyPI its rebuilt and included in that build? I want to make sure it all still works.

**Comment by grovduck** [comment]
Hi Nathan, the .so file is specific to *nix builds (I assume you're on Mac or Linux?) and it's a compiled file.  Windows compiles *.pyd files from the Cython *.pyx files.  When I do `python setup.py build` or `python setup.py install`, it creates this file.  

You can create binary installers for PyPi that include the *.so file, so that folks don't have to build their own, but I think you want to exclude any built files from your repo.  Does this help?  Let me know what happens when you try to build this commit on your machine.

**Comment by Auerilas** [comment]
Hey Matt,

Removing the .so broke it on my build because I couldn't import the _isotonic_regression function. To get it working again I had to rebuild the .pyx file from the terminal using the isoFunc_setup.py

python isoFunc_setup.py build_ext --inplace

as described on the Cython website. That's how I did it originally. I don't know much about this stuff, but I wonder if there's a way to execute the isoFunc_setup.py on build? Or perhaps put the Cython code in the master setup.py file? I would think that the latter is possible, but I don't know how to do that.

**Comment by Auerilas** [comment]
Ok I just went through your setup.py file and it looks like you did add the Cython code in there. But it doesn't seem to be operating. If I force the reinstall:

pip install ecopy -e . --upgrade --force-reinstall

the module installs fine and the .pyx file compiles to the .c file but it doesn't generate the .so file.

**Comment by Auerilas** [comment]
Nevermind. I'm an idiot.

pip install ecopy -e . uses the version uploaded to pip

pip install -e . uses the latest git repo version. That one works fine.

**Comment by grovduck** [comment]
Excellent.  You should also be able to do `python setup.py develop` and that should build both the Cython extensions and create the package in place.  It registers the package with your python install as well - you should have an entry for ecopy at `site-packages/easy_install.pth` as well as an `.egg-info` folder in your root directory.  I'm sure there are things that I'm missing as well, but glad to know you were able to have it build.

**Pull request merged**
